### ISSUE TITLE
Should we make some style guides Rails specific?

### ISSUE THREAD

**Issue by sebasoga** [cookpad/global-style-guides#112]
[This PR](https://github.com/cookpad/global-style-guides/pull/111) adding Phyton made me realize that we have been using this repository to keep style guides for the _web chapter_. Since that's no longer the case maybe we should move some of the guidelines to some folder to make their scope clearer.

That would mean:
- Moving `testing/README.md` to `rails/testing/README.md` or even `ruby/testing/README.md`
- Moving `rake/README.md` to `rails/testing/README.md`

What do you think?

**Comment by lewispb** [comment]
That sounds like a good idea @sebasoga! :)

**Comment by balvig** [comment]
👍 maybe testing could become `rspec/README.md`, since (to my great sadness) that is what we're mainly using and the guides in there address that.

(Not sure what you mean with moving the `rake/README.md`?)

**Comment by sebasoga** [comment]
@balvig I opened a PR following your suggestion https://github.com/cookpad/global-style-guides/issues/112. 

The reason to suggest moving them into the `ruby` folder was based on thinking that tool specific guidelines might fit better "namespacing" them to their language. I'm not doing that now, we could do it later if we see fit.
