### ISSUE TITLE
Make dedicated branch for staging-mobile to share one server with all sprint teams

### ISSUE THREAD

**Issue by y310** [cookpad/global-style-guides#31]
Re-post from https://ckpd.slack.com/archives/web-dev/p1488386407163541 for better logging.

We have started “sprint” development. Since now multiple teams are working simultaneously, we become to suffer staging resource now.
So I’d like to propose to keep deploying 1 dedicated branch to staging-mobile. 

1. The first person who wants to deploy own branch creates a new branch `staging_mobile` ~`staging_mobile_[week]_sprint` (e.g. `staging_mobile_w10_sprint`)~ from `master` and merge own branch to it
2. Then, when other person wants to deploy own branch, they merge own to `staging_mobile` ~`staging_mobile_w10_sprint`~

If there's no concern, I'd like you to follow this from now 🙏

**Comment by balvig** [comment]
@y310 How is this going so far? We had some problems today where the `staging_mobile` branch was missing some code  from `master`, but the DB had already been migrated so it resulted on 500s on `staging_mobile` 🤔

**Comment by y310** [comment]
Hmm, I think much better than the time we didn't have the rule so far.
Before that, app engineers often confused unstable staging behavior due to different branch deploy.
I still don't come up with a better reasonable idea than this 🤔  (this idea requires manual effort to web engineers though...)

At least, for the latest DB problem, splitting staging and staging-mobile db might solve that.

**Comment by balvig** [comment]
@y310 I see (I thought they were already split!) 😅 

I guess maybe we need to defer to https://github.com/cookpad/global-infra/issues/489 to get this sorted for good. Until then we can solve problems as they occur by resyncing `staging_mobile` with `master`?

**Comment by Knack** [comment]
Yes, from time to time I usually do a `git reset --hard origin/master` and a forced push to `staging_mobile` branch.

**Comment by y310** [comment]
Yes, I think paco's this way is good enough to handle outdated branch (git reset and announce in #mobile-dev)
https://ckpd.slack.com/archives/C3CN9Q49E/p1497967479400595
